#!/bin/bash -l
#PBS -l walltime=00:05:00
#PBS -l mem=100gb
#PBS -l nodes=1:ppn=10
#PBS -M your.email@kuleuven.be
#PBS -m aeb
#PBS -N abyss
#PBS -A lp_bioinfworkshop6dec
##Above you see the PBS headers.
##Here all modules are loaded. 
#module use /apps/leuven/thinking/2015a/modules/all	#This line is similar as the "source switch_to_2015a" command, but historically the source switch did not perform well on cerebro
module load ABySS/2.0.2-foss-2018a

#Here we set some variables, for the processing of the data.
CLONE_DIR="/staging/leuven/stg_00019/workshop";	#This one must be the directory where you performed the git clone
GIT_DIR="$CLONE_DIR/vsc_ngs_workshop";
INPUT_DIR="$GIT_DIR/script_and_data/denovo";
SCRATCH_DIR=$VSC_SCRATCH;
OUTPUT_DIR="$GIT_DIR/results/denovo";

#Here a tmp directory is created, specially for this job
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

#here the fastq.gz file is copied to the TMP_DIR
rsync $INPUT_DIR/*.gz .;
gunzip *gz;

#normal run of the abyss command, using 31 as kmer
abyss-pe name="genome_k31" k=31 se="test_assembly_data.R1.fastq" np=10 j=10;

#cleaning and copy of the results
rm *fastq;	#removal of the input data
mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/* .;
rm -rf $TMP_DIR;
