#!/bin/bash -l
#PBS -l walltime=00:10:00
#PBS -l mem=64gb
#PBS -l nodes=1:ppn=36
#PBS -M your.email@kuleuven.be
#PBS -m aeb
#PBS -N bowtie_mapping
#PBS -A lp_biogenomics

module load Bowtie2/2.3.4.3-foss-2018a
module load SAMtools/

#Here we set some variables, for the processing of the data.
CLONE_DIR="/staging/leuven/stg_00019/workshop";  #This one must be the directory where you performed the git clone
GIT_DIR="$CLONE_DIR/vsc_ngs_workshop";
SAMPLE_DIR="$GIT_DIR/script_and_data/mapping";
SCRATCH_DIR=$VSC_SCRATCH;
OUTPUT_DIR="$GIT_DIR/results/mapping";

GENOME_DIR="/staging/leuven/stg_00019/workshop/vsc_ngs_workshop/genome/genome";	#This must be the directory where the genome index is (see prolog)

#Here a tmp directory is created, specially for this job
mkdir -p $SCRATCH_DIR;
TMPDIR=$SCRATCH_DIR;
TMP_DIR=`mktemp -d -t tmp.XXXXXXXX`;
cd $TMP_DIR;

#This initiates the copy command. Note that here the $SAMPLE variable is used. This variable comes from the sample data file.
rsync -ahr $SAMPLE_DIR/$SAMPLE*.fastq.gz .;
gunzip *gz;
FASTQ_FILE=$TMP_DIR/$SAMPLE".R1.fastq";

#Do the actual mapping, using bowtie2
bowtie2 -q -p 1 --seed 1 --local --rg-id $SAMPLE --rg ID=$SAMPLE --rg LB=$SAMPLE --rg SM=$SAMPLE --rg PU=$SAMPLE --rg PL=illumina --rg CN=GenomicsCoreLeuven -x $GENOME_DIR $FASTQ_FILE > $TMP_DIR/mapped.sam 2> $TMP_DIR/$SAMPLE.bowtie2.log;

rm *fastq;	#clean the tmp directory: remove the input fastq

#BAM modifications
samtools view -bS $TMP_DIR/mapped.sam > $TMP_DIR/mapped.bam;	#sam file to bam file
rm -r $TMP_DIR/mapped.sam;
samtools sort $TMP_DIR/mapped.bam > $TMP_DIR/$SAMPLE.bam;	#sort bam file according to chromosome position (previous in fastq order)
rm -r $TMP_DIR/mapped.bam;
samtools index -b $TMP_DIR/$SAMPLE.bam;		#index the bam file (used for fast access, like in IGV, or with variant calling)
rm $TMP_DIR/$SAMPLE.sorted.bam;

#copy the data to the output
mkdir -p $OUTPUT_DIR;
cd $OUTPUT_DIR;
rsync -ahr $TMP_DIR/$SAMPLE* .;
rm -rf $TMP_DIR;



